name: Backend Deploy

on:
  push:
    branches: [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/backend.yml'

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Deploy Server
      working-directory: './server'
    - run: yarn
