name: Client Deploy

on:
  push:
    paths:
      - "client/**"
      - ".github/workflows/client.yml"
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: client

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Client
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: CI='' yarn run build --if-present
