name: Backend Deploy

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/server.yml"
    branches: [main]

env:
  DB_URL: ${{ secrets.DB_URL }}
  TEST: ${{ secrets.TEST.TEST }}

jobs:
  build:
    runs-on: [self-hosted, server]
    defaults:
      run:
        shell: bash
        working-directory: server

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Server
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Create .env File
        run: |
          touch .env
          echo DB_URL=$DB_URL >> .env
          echo TEST=$TEST >> .env
          cat .env
             
      - run: yarn
      - run: pm2 restart server
